### ISSUE TITLE
要望：既存のオブジェクトをカーブで制御したい

### ISSUE THREAD

**Issue by kazuoaraki** [RanmanEmpire/RM_CurveMorph#12]
現在は平面状のものをカーブに沿わしていますが
モデリング済みの髪の毛や尻尾にカーブを沿わして動かせるようになったら嬉しいです

**Comment by RanmanEmpire** [comment]
こちらの要望ですが、なんとなく文章的に2つの意味を読み取れてしまいますので、それぞれ回答します。

１.「現在は平面状のものをカーブに沿わしていますがモデリング済みの髪の毛や尻尾にカーブを沿わして動かせるようになったら嬉しいです」

「揺れて変形するメッシュからカーブを生成する機能」か「揺れに追従して変形するカーブ機能」が必要かと思われます。
なので、これはソースとなるカーブ側に機能追加が必要となり、RM_CurveMorph側が対応すべき要件ではないと考えています！

2.「モデリング済みの髪の毛や尻尾　”を”　カーブ　”に”　沿わして動かせるようになったら嬉しいです」
現状でも立体的なメッシュも動かせるので、ダウンロードに入っている髪の毛のサンプルデータ見てください！サンプルデータの中に平面上のメッシュの他に立体的なバナナ房とドリルロール髪が入っています
